export const GET_MOVEIS_REQUEST = 'GET_MOVEIS_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILER = 'GET_MOVIES_FAILER';
export const GET_TRENDING_MOVEIS_REQUEST = 'GET_TRENDING_MOVEIS_REQUEST';
export const GET_TRENDING_MOVIES_SUCCESS = 'GET_TRENDING_MOVIES_SUCCESS';
export const GET_TRENDING_MOVIES_FAILER = 'GET_TRENDING_MOVIES_FAILER';
export const SEND_DETAILS = 'SEND_DETAILS';